language: rust

# TODO: find a way to install SDL2 without sudo and disable it:
sudo: true

addons:
  apt:
    update: true
    packages:
    - libasound2-dev

cache: cargo

rust:
  - nightly
  - stable

matrix:
  allow_failures:
    - rust: nightly

os:
    - linux
    - osx

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
        && tar -xzvf SDL2-2.0.5.tar.gz
        && pushd SDL2-2.0.5
        && ./configure --prefix=/usr
        && make
        && sudo make install
        && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update && brew install sdl2;
    fi

script:
  - cargo build --all
  - cargo build --examples --all
  - cargo test --all
