language: rust

# TODO: find a way to install SDL2 without sudo and disable it:
sudo: true

addons:
  apt:
    update: true
    packages:
    - libasound2-dev

cache: cargo

rust:
    - nightly
    - beta
    - stable

matrix:
    allow_failures:
        - rust: nightly

os:
    - linux
    - osx

install:
    # TODO: fix indentation to 4 space somehow
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
        && tar -xzvf SDL2-2.0.5.tar.gz
        && pushd SDL2-2.0.5
        && ./configure --prefix=/usr
        && make
        && sudo make install
        && popd;
      fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
          brew update && brew install sdl2;
      fi

# TODO: test other crates
script:
    - cargo build
    - cargo test
    - cargo build --examples --manifest-path zcomponents/Cargo.toml
