environment:
    matrix:
        # TODO: i686-pc-windows-gnu
        # TODO: x86_64-pc-windows-gnu
        - TARGET: x86_64-pc-windows-msvc

artifacts:
  - path: zemeroth-x86_64-pc-windows-msvc.zip
    name: zemeroth
    type: zip

install:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - set PATH=C:\msys64\mingw32\bin;%PATH%
    - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=C:\msys64\mingw64\bin;%PATH%
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain stable -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - cargo -V

build: false

before_test:
    - cd %TEMP%
    - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
    - 7z x SDL2-devel-2.0.5-VC.zip > nul
    - xcopy SDL2-2.0.5\lib\x64\* %APPVEYOR_BUILD_FOLDER% > nul
    - cd %APPVEYOR_BUILD_FOLDER%

test_script:
    - cargo build --release

after_test:
    - git clone --depth=1 https://github.com/ozkriff/zemeroth_assets assets
    - copy target\release\zemeroth.exe zemeroth.exe
    - dir
    - 7z a zemeroth-x86_64-pc-windows-msvc.zip zemeroth.exe SDL2.dll README.md assets

cache:
    - target -> Cargo.lock
    - C:\Users\appveyor\.cargo\registry -> Cargo.lock
