environment:
    matrix:
        - TARGET: x86_64-pc-windows-msvc
        - TARGET: i686-pc-windows-msvc

artifacts:
  - path: zemeroth-%TARGET%.zip
    name: zemeroth
    type: zip

install:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - set PATH=C:\msys64\mingw32\bin;%PATH%
    - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=C:\msys64\mingw64\bin;%PATH%
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain stable -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - cargo -V

build: false

test_script:
    - cargo build --release

after_test:
    - git clone --depth=1 https://github.com/ozkriff/zemeroth_assets assets
    - del /f /q assets\.git
    - copy target\release\zemeroth.exe zemeroth.exe
    - dir
    - 7z a zemeroth-%TARGET%.zip zemeroth.exe README.md assets

cache:
    - target -> Cargo.lock
    - C:\Users\appveyor\.cargo\registry -> Cargo.lock
