[package]
name = "zemeroth"
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
license = "MIT/Apache-2.0"

[workspace]
members = ["hate", "rancor"]

[dependencies]
hate = { path = "hate" }
rancor = { path = "rancor" }
cgmath = "0.15"
ron = "0.1"
rand = "0.3"
log = "0.3"
env_logger = "0.4"
serde = "1.0"
serde_derive = "1.0"

[package.metadata.android]
assets = "assets"
fullscreen = true

[package.metadata.android.activity_attributes]
"android:screenOrientation" = "sensorLandscape"
