version: 2

jobs:
  test:
    working_directory: ~/tgst
    docker:
      - image: tomaka/cargo-apk
    steps:
      - checkout
      - run: cargo apk build

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
